### ISSUE TITLE
Response Issue

### ISSUE THREAD

**Issue by PrinceJamesss** [kacperkwapisz/supreme-api-rewritten#1]
Currently all requests to the website are returning "No Response From Website" via the terminal.

**Comment by kacperkwapisz** [comment]
Hi there @PrinceJamesss,
I've checked, it should work, maybe you are doing something wrong? Could you give me an example of what you are doing? 

Try copying or running the `example.js` file & check if it works.

**Comment by PrinceJamesss** [comment]
Still running into the error. It has to be something here locally in my mind. I've asked someone else to download the repo and give It a shot. I shot you an email earlier as well. I was actually working on something similar, and then found this today. It expedites my process a lot. I'm afraid with some of the work I had done, I've gotten myself blocked from making requests. If It works for the other party, I'll move to a VM or a proxy.

**Comment by kacperkwapisz** [comment]
Hi there, yea it is possible that you run yourself into getting blocked. I'm working on a proxy feature to prevent this kind of problems.
